### PR TITLE
Fix PPS tests

### PR DESCRIPTION
**Pull request by asmecher**
This doesn't fix the Travis tests completely, but nonetheless does fix a number of issues and is ready for review/merge. (I fixed a couple of related issues in pkp-lib but didn't include a submodule update.)

### CODE REVIEW

**Comment by asmecher** [comment]
Correction: the tests now work! Merge this and add a `pkp-lib` submodule update and we should be ready to go.

**Comment by ajnyga** [comment]
@asmecher Can I run the tests now from my own branch?

**Comment by asmecher** [comment]
Do you mean on your own machine, or using Travis?

**Comment by ajnyga** [comment]
I mean if I have my local PPS/pkp-lib/ui-lib branches, then can I start tests based on those here in github using the Submodule update command?

**Comment by asmecher** [comment]
I think you'll just need to set up Travis-CI to run on your `ajnyga` fork of OJS. Because your `pkp-lib` is unmodified, you shouldn't need to do anything related to the submodule. I've just pushed up to my own fork and we'll see if it works: https://travis-ci.org/asmecher/ojs/builds/618714122

**Pull request merged**
